### ISSUE TITLE
Why is a lock released in the next tick?

### ISSUE THREAD

**Issue by bileslav** [amphp/sync#22]
Hi there,

I needed to adapt some of the stuff from this package to work with ReactPHP and it works fine,
but I'm not sure I understand the purpose of this line:

https://github.com/amphp/sync/blob/f41cf7fd91018e436ac76da710f157e968dbf750/src/Lock.php#L48

Why is it done this way?

**Comment by kelunik** [comment]
`EventLoop::queue` isn't really "next tick", but rather once the event loop regains control, even in the same tick. This is done, because `release` is likely called from destructors, which aren't allowed to switch fibers, but it might be better to move `EventLoop::queue` to the destructor and not do an async release if `release` is called manually.

**Comment by bileslav** [comment]
@kelunik Oh, now I understand.

> destructors, which aren't allowed to switch fibers

I didn't know that, very useful information!

Thanks!

**Comment by kelunik** [comment]
Let's change this in the next beta to release only async in the destructor.

**Comment by kelunik** [comment]
This has been fixed in the above commit. :tada:
